// proto/tictactoe.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/tictactoe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameStatus int32

const (
	GameStatus_PENDING       GameStatus = 0
	GameStatus_IN_PROGRESS   GameStatus = 1
	GameStatus_FINISHED_WIN  GameStatus = 2
	GameStatus_FINISHED_DRAW GameStatus = 3
	GameStatus_ABANDONED     GameStatus = 4
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "PENDING",
		1: "IN_PROGRESS",
		2: "FINISHED_WIN",
		3: "FINISHED_DRAW",
		4: "ABANDONED",
	}
	GameStatus_value = map[string]int32{
		"PENDING":       0,
		"IN_PROGRESS":   1,
		"FINISHED_WIN":  2,
		"FINISHED_DRAW": 3,
		"ABANDONED":     4,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tictactoe_proto_enumTypes[0].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_proto_tictactoe_proto_enumTypes[0]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{0}
}

type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BoardSize     int32                  `protobuf:"varint,2,opt,name=board_size,json=boardSize,proto3" json:"board_size,omitempty"`             // optional, defaults to 3
	WinningLength int32                  `protobuf:"varint,3,opt,name=winning_length,json=winningLength,proto3" json:"winning_length,omitempty"` // optional, defaults to 3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_proto_tictactoe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{0}
}

func (x *StartGameRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartGameRequest) GetBoardSize() int32 {
	if x != nil {
		return x.BoardSize
	}
	return 0
}

func (x *StartGameRequest) GetWinningLength() int32 {
	if x != nil {
		return x.WinningLength
	}
	return 0
}

type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Status        GameStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=tictactoe.GameStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_proto_tictactoe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{1}
}

func (x *StartGameResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *StartGameResponse) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_PENDING
}

func (x *StartGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchPendingGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardSize     int32                  `protobuf:"varint,1,opt,name=board_size,json=boardSize,proto3" json:"board_size,omitempty"`             // optional filter
	WinningLength int32                  `protobuf:"varint,2,opt,name=winning_length,json=winningLength,proto3" json:"winning_length,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPendingGamesRequest) Reset() {
	*x = SearchPendingGamesRequest{}
	mi := &file_proto_tictactoe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPendingGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPendingGamesRequest) ProtoMessage() {}

func (x *SearchPendingGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPendingGamesRequest.ProtoReflect.Descriptor instead.
func (*SearchPendingGamesRequest) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{2}
}

func (x *SearchPendingGamesRequest) GetBoardSize() int32 {
	if x != nil {
		return x.BoardSize
	}
	return 0
}

func (x *SearchPendingGamesRequest) GetWinningLength() int32 {
	if x != nil {
		return x.WinningLength
	}
	return 0
}

type SearchPendingGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*PendingGame         `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPendingGamesResponse) Reset() {
	*x = SearchPendingGamesResponse{}
	mi := &file_proto_tictactoe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPendingGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPendingGamesResponse) ProtoMessage() {}

func (x *SearchPendingGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPendingGamesResponse.ProtoReflect.Descriptor instead.
func (*SearchPendingGamesResponse) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{3}
}

func (x *SearchPendingGamesResponse) GetGames() []*PendingGame {
	if x != nil {
		return x.Games
	}
	return nil
}

type PendingGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	CreatorId     string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	BoardSize     int32                  `protobuf:"varint,3,opt,name=board_size,json=boardSize,proto3" json:"board_size,omitempty"`
	WinningLength int32                  `protobuf:"varint,4,opt,name=winning_length,json=winningLength,proto3" json:"winning_length,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingGame) Reset() {
	*x = PendingGame{}
	mi := &file_proto_tictactoe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingGame) ProtoMessage() {}

func (x *PendingGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingGame.ProtoReflect.Descriptor instead.
func (*PendingGame) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{4}
}

func (x *PendingGame) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PendingGame) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *PendingGame) GetBoardSize() int32 {
	if x != nil {
		return x.BoardSize
	}
	return 0
}

func (x *PendingGame) GetWinningLength() int32 {
	if x != nil {
		return x.WinningLength
	}
	return 0
}

func (x *PendingGame) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type JoinGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	mi := &file_proto_tictactoe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{5}
}

func (x *JoinGameRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type JoinGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GameStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=tictactoe.GameStatus" json:"status,omitempty"`
	Game          *Game                  `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	mi := &file_proto_tictactoe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{6}
}

func (x *JoinGameResponse) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_PENDING
}

func (x *JoinGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *JoinGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MakeMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Row           int32                  `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,4,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveRequest) Reset() {
	*x = MakeMoveRequest{}
	mi := &file_proto_tictactoe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRequest) ProtoMessage() {}

func (x *MakeMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRequest.ProtoReflect.Descriptor instead.
func (*MakeMoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{7}
}

func (x *MakeMoveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MakeMoveRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MakeMoveRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *MakeMoveRequest) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

type MakeMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GameStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=tictactoe.GameStatus" json:"status,omitempty"`
	Game          *Game                  `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveResponse) Reset() {
	*x = MakeMoveResponse{}
	mi := &file_proto_tictactoe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveResponse) ProtoMessage() {}

func (x *MakeMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveResponse.ProtoReflect.Descriptor instead.
func (*MakeMoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{8}
}

func (x *MakeMoveResponse) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_PENDING
}

func (x *MakeMoveResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *MakeMoveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameRequest) Reset() {
	*x = GetGameRequest{}
	mi := &file_proto_tictactoe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRequest) ProtoMessage() {}

func (x *GetGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRequest.ProtoReflect.Descriptor instead.
func (*GetGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{9}
}

func (x *GetGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetGameRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameResponse) Reset() {
	*x = GetGameResponse{}
	mi := &file_proto_tictactoe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameResponse) ProtoMessage() {}

func (x *GetGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameResponse.ProtoReflect.Descriptor instead.
func (*GetGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{10}
}

func (x *GetGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_proto_tictactoe_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *UserStats             `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsResponse) Reset() {
	*x = GetUserStatsResponse{}
	mi := &file_proto_tictactoe_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsResponse) ProtoMessage() {}

func (x *GetUserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserStatsResponse) GetStats() *UserStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Game struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Player1Id       string                 `protobuf:"bytes,2,opt,name=player1_id,json=player1Id,proto3" json:"player1_id,omitempty"`
	Player2Id       string                 `protobuf:"bytes,3,opt,name=player2_id,json=player2Id,proto3" json:"player2_id,omitempty"`
	Board           []string               `protobuf:"bytes,4,rep,name=board,proto3" json:"board,omitempty"` // flattened board representation
	BoardSize       int32                  `protobuf:"varint,5,opt,name=board_size,json=boardSize,proto3" json:"board_size,omitempty"`
	WinningLength   int32                  `protobuf:"varint,6,opt,name=winning_length,json=winningLength,proto3" json:"winning_length,omitempty"`
	Status          GameStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=tictactoe.GameStatus" json:"status,omitempty"`
	CurrentPlayerId string                 `protobuf:"bytes,8,opt,name=current_player_id,json=currentPlayerId,proto3" json:"current_player_id,omitempty"`
	WinnerId        string                 `protobuf:"bytes,9,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_proto_tictactoe_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{13}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetPlayer1Id() string {
	if x != nil {
		return x.Player1Id
	}
	return ""
}

func (x *Game) GetPlayer2Id() string {
	if x != nil {
		return x.Player2Id
	}
	return ""
}

func (x *Game) GetBoard() []string {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *Game) GetBoardSize() int32 {
	if x != nil {
		return x.BoardSize
	}
	return 0
}

func (x *Game) GetWinningLength() int32 {
	if x != nil {
		return x.WinningLength
	}
	return 0
}

func (x *Game) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_PENDING
}

func (x *Game) GetCurrentPlayerId() string {
	if x != nil {
		return x.CurrentPlayerId
	}
	return ""
}

func (x *Game) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

func (x *Game) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Game) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UserStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Wins          int32                  `protobuf:"varint,2,opt,name=wins,proto3" json:"wins,omitempty"`
	Losses        int32                  `protobuf:"varint,3,opt,name=losses,proto3" json:"losses,omitempty"`
	Draws         int32                  `protobuf:"varint,4,opt,name=draws,proto3" json:"draws,omitempty"`
	TotalGames    int32                  `protobuf:"varint,5,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	mi := &file_proto_tictactoe_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tictactoe_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_proto_tictactoe_proto_rawDescGZIP(), []int{14}
}

func (x *UserStats) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStats) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *UserStats) GetLosses() int32 {
	if x != nil {
		return x.Losses
	}
	return 0
}

func (x *UserStats) GetDraws() int32 {
	if x != nil {
		return x.Draws
	}
	return 0
}

func (x *UserStats) GetTotalGames() int32 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

var File_proto_tictactoe_proto protoreflect.FileDescriptor

const file_proto_tictactoe_proto_rawDesc = "" +
	"\n" +
	"\x15proto/tictactoe.proto\x12\ttictactoe\"q\n" +
	"\x10StartGameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"board_size\x18\x02 \x01(\x05R\tboardSize\x12%\n" +
	"\x0ewinning_length\x18\x03 \x01(\x05R\rwinningLength\"u\n" +
	"\x11StartGameResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.tictactoe.GameStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"a\n" +
	"\x19SearchPendingGamesRequest\x12\x1d\n" +
	"\n" +
	"board_size\x18\x01 \x01(\x05R\tboardSize\x12%\n" +
	"\x0ewinning_length\x18\x02 \x01(\x05R\rwinningLength\"J\n" +
	"\x1aSearchPendingGamesResponse\x12,\n" +
	"\x05games\x18\x01 \x03(\v2\x16.tictactoe.PendingGameR\x05games\"\xaa\x01\n" +
	"\vPendingGame\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12\x1d\n" +
	"\n" +
	"board_size\x18\x03 \x01(\x05R\tboardSize\x12%\n" +
	"\x0ewinning_length\x18\x04 \x01(\x05R\rwinningLength\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"C\n" +
	"\x0fJoinGameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"\x80\x01\n" +
	"\x10JoinGameResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.tictactoe.GameStatusR\x06status\x12#\n" +
	"\x04game\x18\x02 \x01(\v2\x0f.tictactoe.GameR\x04game\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"g\n" +
	"\x0fMakeMoveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x10\n" +
	"\x03row\x18\x03 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x04 \x01(\x05R\x03col\"\x80\x01\n" +
	"\x10MakeMoveResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.tictactoe.GameStatusR\x06status\x12#\n" +
	"\x04game\x18\x02 \x01(\v2\x0f.tictactoe.GameR\x04game\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"B\n" +
	"\x0eGetGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"6\n" +
	"\x0fGetGameResponse\x12#\n" +
	"\x04game\x18\x01 \x01(\v2\x0f.tictactoe.GameR\x04game\".\n" +
	"\x13GetUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\x14GetUserStatsResponse\x12*\n" +
	"\x05stats\x18\x01 \x01(\v2\x14.tictactoe.UserStatsR\x05stats\"\xe6\x02\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"player1_id\x18\x02 \x01(\tR\tplayer1Id\x12\x1d\n" +
	"\n" +
	"player2_id\x18\x03 \x01(\tR\tplayer2Id\x12\x14\n" +
	"\x05board\x18\x04 \x03(\tR\x05board\x12\x1d\n" +
	"\n" +
	"board_size\x18\x05 \x01(\x05R\tboardSize\x12%\n" +
	"\x0ewinning_length\x18\x06 \x01(\x05R\rwinningLength\x12-\n" +
	"\x06status\x18\a \x01(\x0e2\x15.tictactoe.GameStatusR\x06status\x12*\n" +
	"\x11current_player_id\x18\b \x01(\tR\x0fcurrentPlayerId\x12\x1b\n" +
	"\twinner_id\x18\t \x01(\tR\bwinnerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\x87\x01\n" +
	"\tUserStats\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04wins\x18\x02 \x01(\x05R\x04wins\x12\x16\n" +
	"\x06losses\x18\x03 \x01(\x05R\x06losses\x12\x14\n" +
	"\x05draws\x18\x04 \x01(\x05R\x05draws\x12\x1f\n" +
	"\vtotal_games\x18\x05 \x01(\x05R\n" +
	"totalGames*^\n" +
	"\n" +
	"GameStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x01\x12\x10\n" +
	"\fFINISHED_WIN\x10\x02\x12\x11\n" +
	"\rFINISHED_DRAW\x10\x03\x12\r\n" +
	"\tABANDONED\x10\x042\xda\x03\n" +
	"\x10TicTacToeService\x12F\n" +
	"\tStartGame\x12\x1b.tictactoe.StartGameRequest\x1a\x1c.tictactoe.StartGameResponse\x12a\n" +
	"\x12SearchPendingGames\x12$.tictactoe.SearchPendingGamesRequest\x1a%.tictactoe.SearchPendingGamesResponse\x12C\n" +
	"\bJoinGame\x12\x1a.tictactoe.JoinGameRequest\x1a\x1b.tictactoe.JoinGameResponse\x12C\n" +
	"\bMakeMove\x12\x1a.tictactoe.MakeMoveRequest\x1a\x1b.tictactoe.MakeMoveResponse\x12@\n" +
	"\aGetGame\x12\x19.tictactoe.GetGameRequest\x1a\x1a.tictactoe.GetGameResponse\x12O\n" +
	"\fGetUserStats\x12\x1e.tictactoe.GetUserStatsRequest\x1a\x1f.tictactoe.GetUserStatsResponseB\x11Z\x0ftictactoe/protob\x06proto3"

var (
	file_proto_tictactoe_proto_rawDescOnce sync.Once
	file_proto_tictactoe_proto_rawDescData []byte
)

func file_proto_tictactoe_proto_rawDescGZIP() []byte {
	file_proto_tictactoe_proto_rawDescOnce.Do(func() {
		file_proto_tictactoe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tictactoe_proto_rawDesc), len(file_proto_tictactoe_proto_rawDesc)))
	})
	return file_proto_tictactoe_proto_rawDescData
}

var file_proto_tictactoe_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_tictactoe_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_tictactoe_proto_goTypes = []any{
	(GameStatus)(0),                    // 0: tictactoe.GameStatus
	(*StartGameRequest)(nil),           // 1: tictactoe.StartGameRequest
	(*StartGameResponse)(nil),          // 2: tictactoe.StartGameResponse
	(*SearchPendingGamesRequest)(nil),  // 3: tictactoe.SearchPendingGamesRequest
	(*SearchPendingGamesResponse)(nil), // 4: tictactoe.SearchPendingGamesResponse
	(*PendingGame)(nil),                // 5: tictactoe.PendingGame
	(*JoinGameRequest)(nil),            // 6: tictactoe.JoinGameRequest
	(*JoinGameResponse)(nil),           // 7: tictactoe.JoinGameResponse
	(*MakeMoveRequest)(nil),            // 8: tictactoe.MakeMoveRequest
	(*MakeMoveResponse)(nil),           // 9: tictactoe.MakeMoveResponse
	(*GetGameRequest)(nil),             // 10: tictactoe.GetGameRequest
	(*GetGameResponse)(nil),            // 11: tictactoe.GetGameResponse
	(*GetUserStatsRequest)(nil),        // 12: tictactoe.GetUserStatsRequest
	(*GetUserStatsResponse)(nil),       // 13: tictactoe.GetUserStatsResponse
	(*Game)(nil),                       // 14: tictactoe.Game
	(*UserStats)(nil),                  // 15: tictactoe.UserStats
}
var file_proto_tictactoe_proto_depIdxs = []int32{
	0,  // 0: tictactoe.StartGameResponse.status:type_name -> tictactoe.GameStatus
	5,  // 1: tictactoe.SearchPendingGamesResponse.games:type_name -> tictactoe.PendingGame
	0,  // 2: tictactoe.JoinGameResponse.status:type_name -> tictactoe.GameStatus
	14, // 3: tictactoe.JoinGameResponse.game:type_name -> tictactoe.Game
	0,  // 4: tictactoe.MakeMoveResponse.status:type_name -> tictactoe.GameStatus
	14, // 5: tictactoe.MakeMoveResponse.game:type_name -> tictactoe.Game
	14, // 6: tictactoe.GetGameResponse.game:type_name -> tictactoe.Game
	15, // 7: tictactoe.GetUserStatsResponse.stats:type_name -> tictactoe.UserStats
	0,  // 8: tictactoe.Game.status:type_name -> tictactoe.GameStatus
	1,  // 9: tictactoe.TicTacToeService.StartGame:input_type -> tictactoe.StartGameRequest
	3,  // 10: tictactoe.TicTacToeService.SearchPendingGames:input_type -> tictactoe.SearchPendingGamesRequest
	6,  // 11: tictactoe.TicTacToeService.JoinGame:input_type -> tictactoe.JoinGameRequest
	8,  // 12: tictactoe.TicTacToeService.MakeMove:input_type -> tictactoe.MakeMoveRequest
	10, // 13: tictactoe.TicTacToeService.GetGame:input_type -> tictactoe.GetGameRequest
	12, // 14: tictactoe.TicTacToeService.GetUserStats:input_type -> tictactoe.GetUserStatsRequest
	2,  // 15: tictactoe.TicTacToeService.StartGame:output_type -> tictactoe.StartGameResponse
	4,  // 16: tictactoe.TicTacToeService.SearchPendingGames:output_type -> tictactoe.SearchPendingGamesResponse
	7,  // 17: tictactoe.TicTacToeService.JoinGame:output_type -> tictactoe.JoinGameResponse
	9,  // 18: tictactoe.TicTacToeService.MakeMove:output_type -> tictactoe.MakeMoveResponse
	11, // 19: tictactoe.TicTacToeService.GetGame:output_type -> tictactoe.GetGameResponse
	13, // 20: tictactoe.TicTacToeService.GetUserStats:output_type -> tictactoe.GetUserStatsResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_tictactoe_proto_init() }
func file_proto_tictactoe_proto_init() {
	if File_proto_tictactoe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tictactoe_proto_rawDesc), len(file_proto_tictactoe_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tictactoe_proto_goTypes,
		DependencyIndexes: file_proto_tictactoe_proto_depIdxs,
		EnumInfos:         file_proto_tictactoe_proto_enumTypes,
		MessageInfos:      file_proto_tictactoe_proto_msgTypes,
	}.Build()
	File_proto_tictactoe_proto = out.File
	file_proto_tictactoe_proto_goTypes = nil
	file_proto_tictactoe_proto_depIdxs = nil
}
